import type { NextPage } from 'next'
import Head from 'next/head'
import StatisticalCard from '~/modules/Statistical/index'
import styles from './styles.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StatisticalCard borderColor='#3578f4' color='#4881ea' type='bar' title='THỐNG KÊ SỐ LƯỢN BÀI ĐĂNG THEO KHU VỰC' description='Đánh giá độ năng động của thị trường theo khu vực cụ thể' label='Độ năng động'/>
      <StatisticalCard borderColor='#e65d1d' color='#e65d1d' type='bar' title='MỨC GIÁ TRUNG BÌNH THEO KHU VỰC' description='(Đánh giá sự chênh lệch của giá thị trường theo từng khu vực cụ thể)' label='Sự chênh lệch'/>
      <StatisticalCard borderColor='#f48585' color='#f9aaaa' type='line' title='MỨC ĐỘ TĂNG GIÁ THEO GIAI ĐOẠN KHU VỰC' description='(Đánh giá biến động thị trường theo khu vực cụ thể)' label='Độ biến động'/>
    </div>
  )
}

export default Home