import type { NextPage } from 'next'
import Head from 'next/head'
import StatisticalCard from '~/modules/Statistical/index'
import styles from './styles.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StatisticalCard/>
      <StatisticalCard/>
      <StatisticalCard/>
    </div>
  )
}

export default Home
